### ISSUE TITLE
Error Sending email using gmail

### ISSUE THREAD

**Issue by nia2202** [tghosth/CTFd-docker-deploy#1]
Getting ERROR-3 when trying to use the send mail feature using smtp.gmail.com both SSL and TLS (port 465 and 587) with authentication.

**Comment by tghosth** [comment]
I'm thinking you probably want to raise this on the [main CTFd repository issues list here](https://github.com/CTFd/CTFd/issues) with some more info about your configuration and stuff unless you have reason to believe this is an issue specific to my deployment script. Thanks :)

**Comment by nia2202** [comment]
Yeah, raised the issue to the main repository. Great work on the deployment script. Love it.

**Comment by tghosth** [comment]
Thanks @nia2202, nice to hear :)
