### ISSUE TITLE
Running in plain HTTP without HTTPS

### ISSUE THREAD

**Issue by Halfeez92** [tghosth/CTFd-docker-deploy#11]
Hi is there any config I need to change if I want to run the docker in plain HTTP? I tried editing the nginx.conf and all I got is ERR_EMPTY_RESPONSE

**Comment by tghosth** [comment]
I think in my original blog post I talk about running just using HTTP
https://joshcgrossman.com/2018/03/15/setting-up-an-owasp-juice-shop-ctf/

Does that help?
