### ISSUE TITLE
ERROR: Service 'ctfd' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 137

### ISSUE THREAD

**Issue by cs-ahmed** [tghosth/CTFd-docker-deploy#12]
I am trying to spin up a CTFd environment with SSL. I have "ctfd.crt" in /etc/certs.  I have "ctfd.key" in /etc/private/. And, I have both files in the ssl directory under the CTFd-docker-deploy directory.

When I run
sudo docker-compose -f docker-compose.yml up

I receive the following error:
ERROR: Service 'ctfd' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 137

Screenshot:
<img width="946" alt="ERROR" src="https://user-images.githubusercontent.com/27076142/85633504-5e584d80-b647-11ea-8e7a-2bac14252c6d.png">

Help would be really appreciated!

**Comment by tghosth** [comment]
Thanks for raising this issue and apologies for the delay in response.

The DockerFile was out of date which was causing issues. I have updated everything so it should all work now.

Please open another issue if you still see problems and thanks again!
