### ISSUE TITLE
Can't upload Logo   and   Can't import file (from backup)

### ISSUE THREAD

**Issue by cs-ahmed** [tghosth/CTFd-docker-deploy#13]
Hello again!

So, once I get CTFd up and running, I try to upload a Logo which never finishes and gives the following error in the server:

### PermissionError: [Errno 13] Permission denied: '/var/uploads/a_long_random_number'

![PermissionError](https://user-images.githubusercontent.com/27076142/88984139-d810d600-d29a-11ea-967c-5d5da64a7bd5.png)

This also happened when I try to **IMPORT** a CTFd export file which I have from a previous CTF.

I looked up the error online, but didn't find a solution that works.

I would appreciate it if you can help.

**Comment by tghosth** [comment]
Thanks for sticking with this.

There was some sort of bug related to file permissions. I am not sure where exactly it came from but I have just done a major rework of the way this repository works to try and avoid this sort of thing in the future by mostly using the original CTFd files rather than copies.

I would suggest you clear your existing containers/images and also re-clone this directory. Note the updated instructions which require you to also clone/copy the CTFd repo into the same folder as this one. 

Hope this works better for you. If anything is unclear, please let me know!

**Comment by cs-ahmed** [comment]
Thanks for your attention.

After I follow all the instructions and run:
`sudo run-tls.sh`
 or 
`sudo docker-compose -f docker-compose.yml -f docker-compose-production.yml up -d`
screenshot:
![Screen Shot 2020-08-02 at 6 32 37 PM](https://user-images.githubusercontent.com/27076142/89133947-8fe9f180-d4ee-11ea-9c54-30cba525fff1.png)

I get a `502 Bad Gateway` error when I visit the https site.
![Screen Shot 2020-08-02 at 6 33 46 PM](https://user-images.githubusercontent.com/27076142/89133964-b90a8200-d4ee-11ea-9a96-d76ed8524c47.png)

Kindly notice that this is also the case when running without TLS.

**Comment by cs-ahmed** [comment]
When I run
`sudo docker-compose -f docker-compose.yml -f docker-compose-production.yml up`

I get this:
![Screen Shot 2020-08-02 at 6 38 22 PM](https://user-images.githubusercontent.com/27076142/89134027-75644800-d4ef-11ea-9834-a5d731eb02cc.png)

I hope this helps resolving this issue!

**Comment by cs-ahmed** [comment]
Update:

I got it to work after doing the following:

1. I already had a CTFd directory.
2. Copied the `nginx.conf` file into the existing CTFd directory
3. Copied the `ssl` directory (with ctfd.crt and ctfd.key files) into the existing CTFd directory
4. Copied the `docker-compose-production.yml` file from your repo into the existing CTFd directory
5. Ran `sudo docker-compose -f docker-compose.yml -f docker-compose-production.yml up` which resulted into an error
6. Ran `sudo docker-compose -f docker-compose.yml -f docker-compose-production.yml up` and it worked!!!

I am not sure what is going on. But, I wanted to share that with you.

**Comment by tghosth** [comment]
Thanks for your persistence. If you delete all of the original folders, containers, images and everything else and clone everything from scratch, does it work? I am wondering if you had some sort of conflict with old versions.

**Comment by cs-ahmed** [comment]
In fact, I only copied:
- the `nginx.conf` file from your repo
- the `ssl` directory (with ctfd.crt and ctfd.key files)
- the `docker-compose-production.yml` file from your repo
into the working CTFd directory (cloned from CTFd directly)

And, it worked!

Maybe I will try that again sometime in the future! If I did so, I'll document the process :)
